### ISSUE TITLE
Solutions for diff URLs

### ISSUE THREAD

**Issue by kornelski** [davidrjonas/cargo-lockdiff#3]
`.crate` gzipped tarballs contain `.cargo_vcs_info.json`, which may contain `{"git": { "sha1": "commit hash" }}` of the commit that the crate claims to have been published from. These files are usually unpacked on disk at `$CARGO_HOME/registry/src/index.crates.io-6f17d22bba15001f/$crate-$version/.cargo_vcs_info.json`

However, crates-io allows uploading any code from anywhere and claiming any repo/hash for it, so there's no guarantee that the git URLs are accurate.

https://diff.rs/ site shows diffs of the actual files that have been uploaded to crates-io.

**Comment by davidrjonas** [comment]
Hey, this is really great. I hadn't heard of diff.rs but looks like it'll work perfectly.  I'll incorporate it soon.

**Comment by davidrjonas** [comment]
Released in 0.4.0. Thanks for the suggestion!
